name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Core
        uses: quantixed/metrics@master
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Full history calendar
        uses: quantixed/metrics@master
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: quantixed
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_calendar: yes
          plugin_calendar_limit: 3
